[package]
name = "crdt"
version = "0.3.5"
edition = "2021"

[dependencies]
tinyvec = { version = "1.6.0", features = [ "alloc" ] }
itertools = "0.11.0"
fastrand = "2.0.0"

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"

